package main

import (
	"fmt"
	"log"
	"os"
)

var LOGFILE = "./myLog.log"

func main() {

	// The Golang OS package OpenFile function opens files using flags and permissions.
	// One of the three flags below must be provided: O_RDONLY, O_CREATE, O_RDWR
	// 0644: File mode
	f, err := os.OpenFile(LOGFILE, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)

	// Check error
	if err != nil {
		fmt.Println(err)
		return
	}
	// Close the LOGFILE before main function ends
	defer f.Close()

	// log.New : Create a new logger with three parameters - 1) log file 2) prefix 3) flag(logging property)
	myDateLog := log.New(f, "My Custom Log Created At: ", log.Ldate)
	myTimeLog := log.New(f, "My Custom Log Written at: ", log.Ltime)

	// Create log entries
	myDateLog.Println("Hello Logger!")
	myTimeLog.Println("Good bye Logger!")

	// The flags(logging properties) define which text to prefix to each log entry generated by the Logger.
	// For example, flags Ldate | Ltime (or LstdFlags) produce,
	//	2009/01/23 01:23:23 message
	// while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
	//	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message

}
